class_name WeaponDB
# Single source of truth for every weapon and the rarity system.
# player.gd fires from it, pickup.gd draws from it, hud.gd names from it,
# main.gd rolls pickups from it.

enum Weapon {
	SHOTGUN, PISTOL, SMG, SNIPER,
	UZI, AK47, M4, SAWED_OFF, REVOLVER,
	DEAGLE, SCAR, P90, VECTOR, SPAS,
	GRENADE_LAUNCHER, RPG,
}

enum Rarity { COMMON, UNCOMMON, RARE, EPIC, LEGENDARY }

const RARITY_NAMES := {
	Rarity.COMMON: "Common",
	Rarity.UNCOMMON: "Uncommon",
	Rarity.RARE: "Rare",
	Rarity.EPIC: "Epic",
	Rarity.LEGENDARY: "Legendary",
}

const RARITY_COLORS := {
	Rarity.COMMON: Color(0.75, 0.78, 0.8),
	Rarity.UNCOMMON: Color(0.35, 0.9, 0.4),
	Rarity.RARE: Color(0.3, 0.6, 1.0),
	Rarity.EPIC: Color(0.75, 0.4, 1.0),
	Rarity.LEGENDARY: Color(1.0, 0.65, 0.15),
}

# Out of 100: roughly half the guns you trip over are commons, a
# legendary shows up once in fifty.
const RARITY_WEIGHTS := {
	Rarity.COMMON: 42,
	Rarity.UNCOMMON: 30,
	Rarity.RARE: 18,
	Rarity.EPIC: 8,
	Rarity.LEGENDARY: 2,
}

const SND_SHOTGUN := preload("res://audio/gunsounds/20 Gauge/MP3/20 Gauge Single Isolated.mp3")
const SND_PISTOL := preload("res://audio/gunsounds/9mm/MP3/9mm Single Isolated.mp3")
const SND_556 := preload("res://audio/gunsounds/5.56/MP3/556 Single Isolated MP3.mp3")
const SND_762X39 := preload("res://audio/gunsounds/7.62x39/MP3/762x39 Single Isolated MP3.mp3")
# (.22LR and .308 folders start with a dot, which Godot treats as
# hidden and never imports — heavy guns reuse the 7.62 cracks instead.)
const SND_762X54 := preload("res://audio/gunsounds/7.62x54R/MP3/762x54r Single Isolated MP3.mp3")

# Every weapon: name, rarity, art/handling offsets, ammo, and ballistics.
# fire_mode: "pellets" (default) or "beam". Pellets with explode_radius > 0
# detonate; bounces > 0 ricochet off rocks/walls until the fuse runs out.
# no_drop weapons never spawn as pickups. spin_kick adds the shotgun's
# random body-spin on fire.
const DATA := {
	Weapon.SHOTGUN: {
		"name": "Shotgun",
		"rarity": Rarity.COMMON,
		"texture": preload("res://assets/guns-assetpack/Shotguns/MP-133.png"),
		"recoil": 600.0,
		"cooldown": 0.4,
		"shake": 9.0,
		"kick": 10.0,
		"sprite_x": 26.0,
		"sprite_scale": 0.85,
		"muzzle_x": 66.0,
		"muzzle_y": -5.0,
		"max_ammo": 24,
		"pickup_ammo": 4,
		"damage": 6.0,
		"count": 12,
		"spread_deg": 8.0,
		"speed_min": 900.0,
		"speed_max": 1500.0,
		"proj_life": 0.45,
		"proj_damping": 1400.0,
		"proj_color": Color(1.0, 0.92, 0.6),
		"sound": SND_SHOTGUN,
		"pitch": 1.0,
		"smoke": 14,
		"smoke_scale": 1.0,
		"spin_kick": true,
	},
	Weapon.PISTOL: {
		"name": "Pistol",
		"rarity": Rarity.COMMON,
		"no_drop": true,
		"texture": preload("res://assets/guns-assetpack/Handguns/M1911.png"),
		"recoil": 80.0,
		"cooldown": 0.5,
		"shake": 3.0,
		"kick": 5.0,
		"sprite_x": 16.0,
		"sprite_scale": 1.1,
		"muzzle_x": 34.0,
		"muzzle_y": -5.0,
		"max_ammo": -1,
		"pickup_ammo": 0,
		"damage": 8.0,
		"count": 1,
		"spread_deg": 0.0,
		"speed_min": 650.0,
		"speed_max": 650.0,
		"proj_life": 0.16,
		"proj_damping": 0.0,
		"proj_color": Color(1.0, 0.95, 0.8),
		"sound": SND_PISTOL,
		"pitch": 1.0,
		"smoke": 5,
		"smoke_scale": 0.6,
	},
	Weapon.SMG: {
		"name": "SMG",
		"rarity": Rarity.COMMON,
		"texture": preload("res://assets/guns-assetpack/SMG's/MP5.png"),
		"recoil": 45.0,
		"cooldown": 0.06,
		"shake": 2.0,
		"kick": 3.0,
		"sprite_x": 22.0,
		"sprite_scale": 0.9,
		"muzzle_x": 49.0,
		"muzzle_y": -7.0,
		"max_ammo": 96,
		"pickup_ammo": 48,
		"damage": 4.0,
		"count": 1,
		"spread_deg": 2.5,
		"speed_min": 1100.0,
		"speed_max": 1100.0,
		"proj_life": 0.35,
		"proj_damping": 0.0,
		"proj_color": Color(1.0, 0.8, 0.45),
		"sound": SND_556,
		"pitch": 1.2,
		"smoke": 2,
		"smoke_scale": 0.5,
	},
	Weapon.SNIPER: {
		"name": "Sniper",
		"rarity": Rarity.RARE,
		"texture": preload("res://assets/guns-pixelart/Sniper-rifle-3.png"),
		"recoil": 1100.0,
		"cooldown": 1.5,
		"shake": 16.0,
		"kick": 14.0,
		"sprite_x": 26.0,
		"sprite_scale": 1.0,
		"muzzle_x": 58.0,
		"muzzle_y": -3.0,
		"max_ammo": 6,
		"pickup_ammo": 3,
		"sound": SND_762X54,
		"pitch": 0.95,
		"fire_mode": "beam",
		"smoke": 20,
		"smoke_scale": 1.5,
	},
	Weapon.UZI: {
		"name": "Uzi",
		"rarity": Rarity.COMMON,
		"texture": preload("res://assets/guns-assetpack/SMG's/UZI.png"),
		"recoil": 35.0,
		"cooldown": 0.05,
		"shake": 1.8,
		"kick": 3.0,
		"sprite_x": 18.0,
		"sprite_scale": 0.95,
		"muzzle_x": 42.0,
		"muzzle_y": -5.0,
		"max_ammo": 120,
		"pickup_ammo": 60,
		"damage": 3.0,
		"count": 1,
		"spread_deg": 4.0,
		"speed_min": 1000.0,
		"speed_max": 1000.0,
		"proj_life": 0.3,
		"proj_damping": 0.0,
		"proj_color": Color(1.0, 0.85, 0.55),
		"sound": SND_PISTOL,
		"pitch": 1.35,
		"smoke": 2,
		"smoke_scale": 0.4,
	},
	Weapon.AK47: {
		"name": "AK-47",
		"rarity": Rarity.UNCOMMON,
		"texture": preload("res://assets/guns-assetpack/Assault Rifles/AK47.png"),
		"recoil": 130.0,
		"cooldown": 0.14,
		"shake": 4.0,
		"kick": 6.0,
		"sprite_x": 24.0,
		"sprite_scale": 0.85,
		"muzzle_x": 58.0,
		"muzzle_y": -7.0,
		"max_ammo": 60,
		"pickup_ammo": 30,
		"damage": 9.0,
		"count": 1,
		"spread_deg": 1.8,
		"speed_min": 1250.0,
		"speed_max": 1250.0,
		"proj_life": 0.5,
		"proj_damping": 0.0,
		"proj_color": Color(1.0, 0.75, 0.4),
		"sound": SND_762X39,
		"pitch": 1.0,
		"smoke": 3,
		"smoke_scale": 0.6,
	},
	Weapon.M4: {
		"name": "M4 Carbine",
		"rarity": Rarity.UNCOMMON,
		"texture": preload("res://assets/guns-assetpack/Assault Rifles/M4 Carbine.png"),
		"recoil": 90.0,
		"cooldown": 0.09,
		"shake": 3.0,
		"kick": 5.0,
		"sprite_x": 24.0,
		"sprite_scale": 0.85,
		"muzzle_x": 58.0,
		"muzzle_y": -7.0,
		"max_ammo": 80,
		"pickup_ammo": 40,
		"damage": 6.5,
		"count": 1,
		"spread_deg": 2.2,
		"speed_min": 1300.0,
		"speed_max": 1300.0,
		"proj_life": 0.45,
		"proj_damping": 0.0,
		"proj_color": Color(1.0, 0.82, 0.5),
		"sound": SND_556,
		"pitch": 1.05,
		"smoke": 3,
		"smoke_scale": 0.6,
	},
	Weapon.SAWED_OFF: {
		"name": "Sawed-Off",
		"rarity": Rarity.UNCOMMON,
		"texture": preload("res://assets/guns-assetpack/Shotguns/Sawed off shotgun.png"),
		"recoil": 950.0,
		"cooldown": 0.7,
		"shake": 12.0,
		"kick": 12.0,
		"sprite_x": 20.0,
		"sprite_scale": 0.9,
		"muzzle_x": 48.0,
		"muzzle_y": -4.0,
		"max_ammo": 12,
		"pickup_ammo": 4,
		"damage": 7.0,
		"count": 14,
		"spread_deg": 16.0,
		"speed_min": 800.0,
		"speed_max": 1300.0,
		"proj_life": 0.3,
		"proj_damping": 1600.0,
		"proj_color": Color(1.0, 0.9, 0.55),
		"sound": SND_SHOTGUN,
		"pitch": 1.15,
		"smoke": 16,
		"smoke_scale": 1.1,
		"spin_kick": true,
	},
	Weapon.REVOLVER: {
		"name": "Revolver",
		"rarity": Rarity.UNCOMMON,
		"texture": preload("res://assets/guns-assetpack/Handguns/Revolver.png"),
		"recoil": 260.0,
		"cooldown": 0.55,
		"shake": 6.0,
		"kick": 9.0,
		"sprite_x": 16.0,
		"sprite_scale": 1.1,
		"muzzle_x": 34.0,
		"muzzle_y": -5.0,
		"max_ammo": 18,
		"pickup_ammo": 6,
		"damage": 22.0,
		"count": 1,
		"spread_deg": 0.0,
		"speed_min": 1400.0,
		"speed_max": 1400.0,
		"proj_life": 0.6,
		"proj_damping": 0.0,
		"proj_color": Color(1.0, 0.9, 0.7),
		"sound": SND_762X54,
		"pitch": 1.3,
		"smoke": 6,
		"smoke_scale": 0.8,
	},
	Weapon.DEAGLE: {
		"name": "Desert Eagle",
		"rarity": Rarity.RARE,
		"texture": preload("res://assets/guns-assetpack/Handguns/Desert Eagle.png"),
		"recoil": 380.0,
		"cooldown": 0.45,
		"shake": 8.0,
		"kick": 10.0,
		"sprite_x": 16.0,
		"sprite_scale": 1.1,
		"muzzle_x": 34.0,
		"muzzle_y": -5.0,
		"max_ammo": 21,
		"pickup_ammo": 7,
		"damage": 30.0,
		"count": 1,
		"spread_deg": 0.0,
		"speed_min": 1500.0,
		"speed_max": 1500.0,
		"proj_life": 0.6,
		"proj_damping": 0.0,
		"proj_color": Color(1.0, 0.95, 0.75),
		"sound": SND_762X54,
		"pitch": 1.1,
		"smoke": 8,
		"smoke_scale": 0.9,
	},
	Weapon.SCAR: {
		"name": "FN SCAR",
		"rarity": Rarity.RARE,
		"texture": preload("res://assets/guns-assetpack/Assault Rifles/FN SCAR.png"),
		"recoil": 180.0,
		"cooldown": 0.16,
		"shake": 5.0,
		"kick": 7.0,
		"sprite_x": 24.0,
		"sprite_scale": 0.85,
		"muzzle_x": 58.0,
		"muzzle_y": -7.0,
		"max_ammo": 60,
		"pickup_ammo": 30,
		"damage": 13.0,
		"count": 1,
		"spread_deg": 1.2,
		"speed_min": 1400.0,
		"speed_max": 1400.0,
		"proj_life": 0.55,
		"proj_damping": 0.0,
		"proj_color": Color(1.0, 0.7, 0.35),
		"sound": SND_762X39,
		"pitch": 1.15,
		"smoke": 3,
		"smoke_scale": 0.6,
	},
	Weapon.P90: {
		"name": "P90",
		"rarity": Rarity.RARE,
		"texture": preload("res://assets/guns-assetpack/SMG's/P90.png"),
		"recoil": 30.0,
		"cooldown": 0.035,
		"shake": 1.6,
		"kick": 2.5,
		"sprite_x": 18.0,
		"sprite_scale": 1.0,
		"muzzle_x": 42.0,
		"muzzle_y": -6.0,
		"max_ammo": 150,
		"pickup_ammo": 50,
		"damage": 3.5,
		"count": 1,
		"spread_deg": 5.0,
		"speed_min": 1100.0,
		"speed_max": 1100.0,
		"proj_life": 0.35,
		"proj_damping": 0.0,
		"proj_color": Color(0.8, 0.9, 1.0),
		"sound": SND_PISTOL,
		"pitch": 1.45,
		"smoke": 2,
		"smoke_scale": 0.4,
	},
	Weapon.VECTOR: {
		"name": "Vector",
		"rarity": Rarity.EPIC,
		"texture": preload("res://assets/guns-assetpack/SMG's/KRISS Vector.png"),
		"recoil": 40.0,
		"cooldown": 0.025,
		"shake": 2.0,
		"kick": 3.0,
		"sprite_x": 20.0,
		"sprite_scale": 0.9,
		"muzzle_x": 44.0,
		"muzzle_y": -8.0,
		"max_ammo": 130,
		"pickup_ammo": 65,
		"damage": 4.0,
		"count": 1,
		"spread_deg": 6.0,
		"speed_min": 1150.0,
		"speed_max": 1150.0,
		"proj_life": 0.3,
		"proj_damping": 0.0,
		"proj_color": Color(0.95, 0.7, 1.0),
		"sound": SND_PISTOL,
		"pitch": 1.6,
		"smoke": 2,
		"smoke_scale": 0.4,
	},
	Weapon.SPAS: {
		"name": "SPAS-12",
		"rarity": Rarity.EPIC,
		"texture": preload("res://assets/guns-assetpack/Shotguns/SPAS Shotgun.png"),
		"recoil": 420.0,
		"cooldown": 0.22,
		"shake": 8.0,
		"kick": 10.0,
		"sprite_x": 22.0,
		"sprite_scale": 0.9,
		"muzzle_x": 49.0,
		"muzzle_y": -5.0,
		"max_ammo": 24,
		"pickup_ammo": 8,
		"damage": 5.5,
		"count": 10,
		"spread_deg": 10.0,
		"speed_min": 900.0,
		"speed_max": 1400.0,
		"proj_life": 0.4,
		"proj_damping": 1400.0,
		"proj_color": Color(1.0, 0.85, 0.5),
		"sound": SND_SHOTGUN,
		"pitch": 1.0,
		"smoke": 10,
		"smoke_scale": 0.9,
		"spin_kick": true,
	},
	Weapon.GRENADE_LAUNCHER: {
		"name": "Grenade Launcher",
		"rarity": Rarity.EPIC,
		"texture": preload("res://assets/guns-pixelart/grenade launcher.png"),
		"recoil": 320.0,
		"cooldown": 0.8,
		"shake": 7.0,
		"kick": 11.0,
		"sprite_x": 24.0,
		"sprite_scale": 1.0,
		"muzzle_x": 56.0,
		"muzzle_y": -4.0,
		"max_ammo": 12,
		"pickup_ammo": 4,
		"damage": 25.0,
		"count": 1,
		"spread_deg": 0.0,
		"speed_min": 700.0,
		"speed_max": 700.0,
		"proj_life": 1.6,
		"proj_damping": 120.0,
		"proj_color": Color(0.6, 1.0, 0.5),
		"proj_scale": 2.0,
		"explode_radius": 140.0,
		"explode_damage": 45.0,
		"bounces": 3,
		"sound": SND_SHOTGUN,
		"pitch": 0.6,
		"smoke": 12,
		"smoke_scale": 1.2,
	},
	Weapon.RPG: {
		"name": "RPG",
		"rarity": Rarity.LEGENDARY,
		"texture": preload("res://assets/guns-pixelart/RPG-reisized.png"),
		"recoil": 1500.0,
		"cooldown": 1.6,
		"shake": 20.0,
		"kick": 16.0,
		"sprite_x": 28.0,
		"sprite_scale": 1.0,
		"muzzle_x": 76.0,
		"muzzle_y": -8.0,
		"max_ammo": 6,
		"pickup_ammo": 2,
		"damage": 40.0,
		"count": 1,
		"spread_deg": 0.0,
		"speed_min": 950.0,
		"speed_max": 950.0,
		"proj_life": 2.5,
		"proj_damping": 0.0,
		"proj_color": Color(1.0, 0.6, 0.25),
		"proj_scale": 2.5,
		"explode_radius": 220.0,
		"explode_damage": 90.0,
		"sound": SND_762X54,
		"pitch": 0.55,
		"smoke": 22,
		"smoke_scale": 1.6,
	},
}


static func rarity_of(id: int) -> int:
	return DATA[id]["rarity"]


static func rarity_color(id: int) -> Color:
	return RARITY_COLORS[rarity_of(id)]


# Weighted rarity roll, then a uniform pick within that tier.
static func roll_weapon() -> int:
	var total := 0
	for w in RARITY_WEIGHTS.values():
		total += w
	var roll := randi() % total
	var tier: int = Rarity.COMMON
	for r in RARITY_WEIGHTS:
		roll -= RARITY_WEIGHTS[r]
		if roll < 0:
			tier = r
			break
	var pool: Array = []
	for id in DATA:
		if DATA[id]["rarity"] == tier and not DATA[id].get("no_drop", false):
			pool.append(id)
	return pool[randi() % pool.size()]
